### ISSUE TITLE
Ben - todo

### ISSUE THREAD

**Issue by bpbond** [AditiGit/BeaverCreek_Test#3]
- [x] Match valve-sample data file to Picarro data 
- [x] Improve diagnostic graphs (@AditiGit can also work on this as she wants)
- [ ] Test out flux computation packages (see #1 )
